<a href="https://colab.research.google.com/github/NikhilBsc/BscTraining/blob/main/14_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1
Natural Language Processing (NLP) is a branch of Artificial Intelligence that helps computers understand, interpret, and generate human language. It acts as a bridge between humans and computers by converting human language into a form that computers can process.

#2
Computers understand numbers and code, not human language. NLP helps convert text or speech into a format that computers can analyze.

Example: Google Translate uses NLP to translate text from one language to another.

#q3
voice Assistants – Applications like Siri and Google Assistant understand voice commands and respond to users.
Text Autocomplete – Suggests words or sentences while typing in emails, messages, or search engines.
Grammar and Spell Checkers – Tools like Grammarly detect spelling and grammar mistakes and suggest corrections.
Text Summarization – Automatically creates a short summary of long articles, documents, or reports.

#q4
A rule-based NLP system follows predefined rules to make decisions.

Example: In spam detection, if a message contains the word "Congratulations", it may be marked as spam based on a fixed rule.

#5
Text Collection – Gather text data.
Text Cleaning – Remove unwanted characters and symbols.
Tokenization – Split text into words or tokens.
Lowercasing – Convert all text to lowercase.
Stopword Removal – Remove common words like "the", "is".
Stemming/Lemmatization – Convert words to their root form.
Feature Extraction & Modeling – Convert text into numbers and train a model.

#q6
okenization is the process of splitting text into smaller units called tokens (usually words).

Example:
"I love NLP" ---> ["I", "love", "NLP"]

It is necessary because machine learning models cannot directly understand raw text.

#q7
stopwords are common words that usually do not add much meaning to a sentence.

Examples: "the", "is", "and"

They are often removed to reduce unnecessary data and improve processing speed.

#q8
Lowercasing ensures that words with different cases are treated as the same word.

Example:
"Apple", "APPLE", and "apple" will all become "apple".

This avoids duplicate representations of the same word.

#q9 common mistakes we make in pandas for NLP
Forgetting to handle missing values.
Not converting text to lowercase.
Using the wrong column name.
Forgetting to save changes back to the DataFrame.

#q10 diff between = and ==
= is used to assign a value.
== is used to compare values.

#Practical section

In [2]:
#q1
sen = "i love artificial intelligence"
print(type(sen))

<class 'str'>

In [6]:
#q2
sen = "i love artificial intelligence"
print(len(sen))

30

In [7]:
#q3
sen = "i love natural language processing"
words = sen.split()
print(len(words))

5

In [2]:
#q4
sen = "you have won a free prize"
if "free" in sen:
  print("yes present")
else:
  print("not present")

yes present

In [3]:
#q5
message = "you have won the lottery , congratulations , enjoy!!"
if "congratulations" in message:
  print("possible spam")
else:
  print("you are safe")

possible spam

In [4]:
#q6
import pandas as pd
data = {"sentiment":["very nice product","battery heating up ","phone case is very nice","worst battery backup"],
        "review":["positive","negative","positive","negative"]}

df = pd.DataFrame(data)
df

                 sentiment    review
0        very nice product  positive
1      battery heating up   negative
2  phone case is very nice  positive
3     worst battery backup  negative

#q7

In [5]:
df.shape

(4, 2)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sentiment  4 non-null      object
 1   review     4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [7]:
#q8
df.head()

                 sentiment    review
0        very nice product  positive
1      battery heating up   negative
2  phone case is very nice  positive
3     worst battery backup  negative

In [8]:
df.tail()

                 sentiment    review
0        very nice product  positive
1      battery heating up   negative
2  phone case is very nice  positive
3     worst battery backup  negative

In [10]:
#q9
print(df["review"].value_counts())

review
positive    2
negative    2
Name: count, dtype: int64

In [13]:
#q10
lower = df["sentiment"].str.lower()
print(lower)

0          very nice product
1        battery heating up
2    phone case is very nice
3       worst battery backup
Name: sentiment, dtype: object

In [14]:
#q11
df["Length"] = df["sentiment"].apply(len)
df

                 sentiment    review  Length
0        very nice product  positive      17
1      battery heating up   negative      19
2  phone case is very nice  positive      23
3     worst battery backup  negative      20

In [16]:
#q12
for reviews in df["sentiment"]:
  print(reviews)

very nice product
battery heating up
phone case is very nice
worst battery backup

In [17]:
#14
#Write a Python statement using str.contains() to check whether the word "phone" appears in each row of a "Review" column.
print(df[df["sentiment"].str.contains("phone")])

                 sentiment    review  Length
2  phone case is very nice  positive      23

In [20]:
#15
df["Words"] = df["sentiment"].apply(lambda x: len(x.split()))
df

                 sentiment    review  Length  Words
0        very nice product  positive      17      3
1      battery heating up   negative      19      3
2  phone case is very nice  positive      23      5
3     worst battery backup  negative      20      3

In [21]:
#16
import pandas as pd
data1 = {"review":["very nice movie","movie is excellent ","climax is worst","best movie","actors didnt perform well","villain shaould have been better"],
        "sentiment":["positive","positive","negative","positive","negative","negative"]}

df1 = pd.DataFrame(data1)
df1

                             review sentiment
0                   very nice movie  positive
1               movie is excellent   positive
2                   climax is worst  negative
3                        best movie  positive
4         actors didnt perform well  negative
5  villain shaould have been better  negative

In [22]:
neg_review = df1[df1["sentiment"] == "negative"]
neg_review

                             review sentiment
2                   climax is worst  negative
4         actors didnt perform well  negative
5  villain shaould have been better  negative

In [28]:
#18
longest_chars = max(df1["review"] , key = len)
longest_chars

'villain shaould have been better'

In [31]:
#19
print(df1["sentiment"].value_counts())

sentiment
positive    3
negative    3
Name: count, dtype: int64

In [32]:
#20
import pandas as pd

data = {
    "feedback": ["The teaching was excellent",
        "I enjoyed the practical sessions",
        "The course was very helpful",
        "Faculty explained concepts clearly",
        "Good learning experience",
        "The classes were boring",
        "Course content was outdated",
        "Too much workload",
        "The explanations were confusing",
        "Not satisfied with the training"
    ],
    "sentiment": [
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative"
    ]
}

df3 = pd.DataFrame(data)
df3

                             feedback sentiment
0          The teaching was excellent  Positive
1    I enjoyed the practical sessions  Positive
2         The course was very helpful  Positive
3  Faculty explained concepts clearly  Positive
4            Good learning experience  Positive
5             The classes were boring  Negative
6         Course content was outdated  Negative
7                   Too much workload  Negative
8     The explanations were confusing  Negative
9     Not satisfied with the training  Negative

In [33]:
print("first 5 rows",df.head(5))

first 5 rows                  sentiment    review  Length  Words
0        very nice product  positive      17      3
1      battery heating up   negative      19      3
2  phone case is very nice  positive      23      5
3     worst battery backup  negative      20      3

In [34]:
print("last 5 rows:",df.tail(5))

last 5 rows:                  sentiment    review  Length  Words
0        very nice product  positive      17      3
1      battery heating up   negative      19      3
2  phone case is very nice  positive      23      5
3     worst battery backup  negative      20      3